### ISSUE TITLE
[Request] folder structure changing

### ISSUE THREAD

**Issue by MaelKoT** [GetLocalPlayer/DressMe#4]
please change a folder structure like in most of other addons?
like move all files into DressMe folder

db -> DressMe/db
frames -> DressMe/frames
images -> DressMe/images
DressMe.lua -> DressMe/DressMe.lua
DressMe.toc -> DressMe/DressMe.toc

**Comment by GetLocalPlayer** [comment]
Hello there! 
> like move all files into DressMe folder

What's the motivation of doing this? The addon itself is "DressMe.lua". I probably can agree with the database files, but "frames" folder contains libraries that are used by the addon and can be imported anywhere else so, as libraries, they're moved in their own folder.

**Comment by MaelKoT** [comment]
It's just something like a standard for wow addons. (elvui, bkaders skada-revisited, bunnys weakauras/details, etc...)

Basically I made a request so DressMe addon can be used with an autoupdater, like https://github.com/Barsoomx/DBM-wowcircle-updater

And this stucture changing will not change anything in the addon itself, nothing at all, the libraries will still be in a separate folder.
All that will change is that users will not need to rename DressMe-master in DressMe, but just inside this DressMe-master folder will be DressMe folder itself with all addon files...
_and I can use auto-update, convenient AF_

**Comment by GetLocalPlayer** [comment]
Aha, understood what you were talking about. Sure.

**Comment by GetLocalPlayer** [comment]
Done.
