### ISSUE TITLE
Item Show in the List

### ISSUE THREAD

**Issue by Noob1e** [GetLocalPlayer/DressMe#5]
Some appearances looking weird.

Head:
![SS](https://user-images.githubusercontent.com/27544010/117628326-af9afe00-b181-11eb-904f-16e11b558057.PNG)

Wrist:
![SS2](https://user-images.githubusercontent.com/27544010/117628361-bd508380-b181-11eb-8fac-e32465adcfbe.PNG)

Waist:
![SS3](https://user-images.githubusercontent.com/27544010/117628381-c17ca100-b181-11eb-9c6b-6d192a3ec926.PNG)

**Comment by GetLocalPlayer** [comment]
Hi!
Looks like the camera on the previews is too close to the model.
What resolution does your game client use in the video settings?

**Comment by Noob1e** [comment]
Hello.
It's 1920x1080 with 0.6 UI scale. I'm also using new character models (we used to have it on Warmane website).

**Comment by GetLocalPlayer** [comment]
Alright, it seems the problem is in the UI scaling factor. I managed to reproduce the problem with almost minimal UI scaling (I'm using non-full HD screen). Please, try to increase UI scaling and tell me the result.

**Comment by Noob1e** [comment]
It looks fine at 1.0 scale but it still looks bad at the other scales.
At 0.5 scale, it even turns the heads.
![SS4](https://user-images.githubusercontent.com/27544010/117653006-918ec700-b19c-11eb-82b7-3bd8657c4643.PNG)

**Comment by GetLocalPlayer** [comment]
Thank you, will see what can i do with it.

**Comment by Noob1e** [comment]
It looks fine with the "ignore UI scale" option. Thank you :)

**Comment by GetLocalPlayer** [comment]
Hope you will enjoy the addon!
